# Generated by Django 4.0.3 on 2024-06-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('basic', 'Basic'), ('professional', 'Professional'), ('specific', 'Specific')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('hours', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.IntegerField(default=1)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.competency')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='competencies',
            field=models.ManyToManyField(through='courses.CourseCompetency', to='courses.competency'),
        ),
    ]
